// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDummy', // 임시값
    appId: '1:123456789:web:dummy',
    messagingSenderId: '123456789',
    projectId: 'myflight-temp',
    authDomain: 'myflight-temp.firebaseapp.com',
    storageBucket: 'myflight-temp.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDummy', // 임시값 - 실제 프로젝트에서는 변경 필요
    appId: '1:123456789:android:dummy',
    messagingSenderId: '123456789',
    projectId: 'myflight-temp',
    storageBucket: 'myflight-temp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDummy', // 임시값 - 실제 프로젝트에서는 변경 필요
    appId: '1:123456789:ios:dummy',
    messagingSenderId: '123456789',
    projectId: 'myflight-temp',
    iosBundleId: 'com.khlee.myflight',
    storageBucket: 'myflight-temp.appspot.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDummy',
    appId: '1:123456789:ios:dummy',
    messagingSenderId: '123456789',
    projectId: 'myflight-temp',
    iosBundleId: 'com.khlee.myflight',
    storageBucket: 'myflight-temp.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDummy',
    appId: '1:123456789:web:dummy',
    messagingSenderId: '123456789',
    projectId: 'myflight-temp',
    authDomain: 'myflight-temp.firebaseapp.com',
    storageBucket: 'myflight-temp.appspot.com',
  );
} 